// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DriverClient is the client API for Driver service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DriverClient interface {
	// TaskConfigSchema returns the schema for parsing the driver
	// configuration of a task.
	TaskConfigSchema(ctx context.Context, in *TaskConfigSchemaRequest, opts ...grpc.CallOption) (*TaskConfigSchemaResponse, error)
	// Capabilities returns a set of features which the driver implements. Some
	// RPCs are not possible to implement on some runtimes, this allows the
	// driver to indicate if it doesn't support these RPCs and features.
	Capabilities(ctx context.Context, in *CapabilitiesRequest, opts ...grpc.CallOption) (*CapabilitiesResponse, error)
	// Fingerprint starts a stream which emits information about the driver
	// including whether the driver healthy and able to function in the
	// existing environment.
	//
	// The driver should immediately stream a FingerprintResponse when the RPC
	// is initially called, then send any additional responses if there is a
	// change in the driver's state.
	Fingerprint(ctx context.Context, in *FingerprintRequest, opts ...grpc.CallOption) (Driver_FingerprintClient, error)
	// RecoverTask is used when a task has been started but the driver may not
	// know about it. Such is the case if the driver restarts or is upgraded.
	RecoverTask(ctx context.Context, in *RecoverTaskRequest, opts ...grpc.CallOption) (*RecoverTaskResponse, error)
	// StartTask starts and tracks the task on the implemented runtime
	StartTask(ctx context.Context, in *StartTaskRequest, opts ...grpc.CallOption) (*StartTaskResponse, error)
	// WaitTask blocks until the given task exits, returning the result of the
	// task. It may be called after the task has exited, but before the task is
	// destroyed.
	WaitTask(ctx context.Context, in *WaitTaskRequest, opts ...grpc.CallOption) (*WaitTaskResponse, error)
	// StopTask stops a given task by sending the desired signal to the process.
	// If the task does not exit on its own within the given timeout, it will be
	// forcefully killed.
	StopTask(ctx context.Context, in *StopTaskRequest, opts ...grpc.CallOption) (*StopTaskResponse, error)
	// DestroyTask removes the task from the driver's internal state and cleans
	// up any additional resources created by the driver. It cannot be called
	// on a running task, unless force is set to true.
	DestroyTask(ctx context.Context, in *DestroyTaskRequest, opts ...grpc.CallOption) (*DestroyTaskResponse, error)
	// InspectTask returns detailed information for the given task
	InspectTask(ctx context.Context, in *InspectTaskRequest, opts ...grpc.CallOption) (*InspectTaskResponse, error)
	// TaskStats collects and returns runtime metrics for the given task
	TaskStats(ctx context.Context, in *TaskStatsRequest, opts ...grpc.CallOption) (Driver_TaskStatsClient, error)
	// TaskEvents starts a streaming RPC where all task events emitted by the
	// driver are streamed to the caller.
	TaskEvents(ctx context.Context, in *TaskEventsRequest, opts ...grpc.CallOption) (Driver_TaskEventsClient, error)
	// SignalTask sends a signal to the task
	SignalTask(ctx context.Context, in *SignalTaskRequest, opts ...grpc.CallOption) (*SignalTaskResponse, error)
	// ExecTask executes a command inside the tasks execution context
	ExecTask(ctx context.Context, in *ExecTaskRequest, opts ...grpc.CallOption) (*ExecTaskResponse, error)
	// ExecTaskStreaming executes a command inside the tasks execution context
	// and streams back results
	// buf:lint:ignore RPC_REQUEST_RESPONSE_UNIQUE
	ExecTaskStreaming(ctx context.Context, opts ...grpc.CallOption) (Driver_ExecTaskStreamingClient, error)
	// CreateNetwork is implemented when the driver needs to create the network
	// namespace instead of allowing the Nomad client to do.
	CreateNetwork(ctx context.Context, in *CreateNetworkRequest, opts ...grpc.CallOption) (*CreateNetworkResponse, error)
	// DestroyNetwork destroys a previously created network. This rpc is only
	// implemented if the driver needs to manage network namespace creation.
	DestroyNetwork(ctx context.Context, in *DestroyNetworkRequest, opts ...grpc.CallOption) (*DestroyNetworkResponse, error)
}

type driverClient struct {
	cc grpc.ClientConnInterface
}

func NewDriverClient(cc grpc.ClientConnInterface) DriverClient {
	return &driverClient{cc}
}

func (c *driverClient) TaskConfigSchema(ctx context.Context, in *TaskConfigSchemaRequest, opts ...grpc.CallOption) (*TaskConfigSchemaResponse, error) {
	out := new(TaskConfigSchemaResponse)
	err := c.cc.Invoke(ctx, "/hashicorp.nomad.plugins.drivers.proto.Driver/TaskConfigSchema", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverClient) Capabilities(ctx context.Context, in *CapabilitiesRequest, opts ...grpc.CallOption) (*CapabilitiesResponse, error) {
	out := new(CapabilitiesResponse)
	err := c.cc.Invoke(ctx, "/hashicorp.nomad.plugins.drivers.proto.Driver/Capabilities", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverClient) Fingerprint(ctx context.Context, in *FingerprintRequest, opts ...grpc.CallOption) (Driver_FingerprintClient, error) {
	stream, err := c.cc.NewStream(ctx, &Driver_ServiceDesc.Streams[0], "/hashicorp.nomad.plugins.drivers.proto.Driver/Fingerprint", opts...)
	if err != nil {
		return nil, err
	}
	x := &driverFingerprintClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Driver_FingerprintClient interface {
	Recv() (*FingerprintResponse, error)
	grpc.ClientStream
}

type driverFingerprintClient struct {
	grpc.ClientStream
}

func (x *driverFingerprintClient) Recv() (*FingerprintResponse, error) {
	m := new(FingerprintResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *driverClient) RecoverTask(ctx context.Context, in *RecoverTaskRequest, opts ...grpc.CallOption) (*RecoverTaskResponse, error) {
	out := new(RecoverTaskResponse)
	err := c.cc.Invoke(ctx, "/hashicorp.nomad.plugins.drivers.proto.Driver/RecoverTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverClient) StartTask(ctx context.Context, in *StartTaskRequest, opts ...grpc.CallOption) (*StartTaskResponse, error) {
	out := new(StartTaskResponse)
	err := c.cc.Invoke(ctx, "/hashicorp.nomad.plugins.drivers.proto.Driver/StartTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverClient) WaitTask(ctx context.Context, in *WaitTaskRequest, opts ...grpc.CallOption) (*WaitTaskResponse, error) {
	out := new(WaitTaskResponse)
	err := c.cc.Invoke(ctx, "/hashicorp.nomad.plugins.drivers.proto.Driver/WaitTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverClient) StopTask(ctx context.Context, in *StopTaskRequest, opts ...grpc.CallOption) (*StopTaskResponse, error) {
	out := new(StopTaskResponse)
	err := c.cc.Invoke(ctx, "/hashicorp.nomad.plugins.drivers.proto.Driver/StopTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverClient) DestroyTask(ctx context.Context, in *DestroyTaskRequest, opts ...grpc.CallOption) (*DestroyTaskResponse, error) {
	out := new(DestroyTaskResponse)
	err := c.cc.Invoke(ctx, "/hashicorp.nomad.plugins.drivers.proto.Driver/DestroyTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverClient) InspectTask(ctx context.Context, in *InspectTaskRequest, opts ...grpc.CallOption) (*InspectTaskResponse, error) {
	out := new(InspectTaskResponse)
	err := c.cc.Invoke(ctx, "/hashicorp.nomad.plugins.drivers.proto.Driver/InspectTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverClient) TaskStats(ctx context.Context, in *TaskStatsRequest, opts ...grpc.CallOption) (Driver_TaskStatsClient, error) {
	stream, err := c.cc.NewStream(ctx, &Driver_ServiceDesc.Streams[1], "/hashicorp.nomad.plugins.drivers.proto.Driver/TaskStats", opts...)
	if err != nil {
		return nil, err
	}
	x := &driverTaskStatsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Driver_TaskStatsClient interface {
	Recv() (*TaskStatsResponse, error)
	grpc.ClientStream
}

type driverTaskStatsClient struct {
	grpc.ClientStream
}

func (x *driverTaskStatsClient) Recv() (*TaskStatsResponse, error) {
	m := new(TaskStatsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *driverClient) TaskEvents(ctx context.Context, in *TaskEventsRequest, opts ...grpc.CallOption) (Driver_TaskEventsClient, error) {
	stream, err := c.cc.NewStream(ctx, &Driver_ServiceDesc.Streams[2], "/hashicorp.nomad.plugins.drivers.proto.Driver/TaskEvents", opts...)
	if err != nil {
		return nil, err
	}
	x := &driverTaskEventsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Driver_TaskEventsClient interface {
	Recv() (*DriverTaskEvent, error)
	grpc.ClientStream
}

type driverTaskEventsClient struct {
	grpc.ClientStream
}

func (x *driverTaskEventsClient) Recv() (*DriverTaskEvent, error) {
	m := new(DriverTaskEvent)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *driverClient) SignalTask(ctx context.Context, in *SignalTaskRequest, opts ...grpc.CallOption) (*SignalTaskResponse, error) {
	out := new(SignalTaskResponse)
	err := c.cc.Invoke(ctx, "/hashicorp.nomad.plugins.drivers.proto.Driver/SignalTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverClient) ExecTask(ctx context.Context, in *ExecTaskRequest, opts ...grpc.CallOption) (*ExecTaskResponse, error) {
	out := new(ExecTaskResponse)
	err := c.cc.Invoke(ctx, "/hashicorp.nomad.plugins.drivers.proto.Driver/ExecTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverClient) ExecTaskStreaming(ctx context.Context, opts ...grpc.CallOption) (Driver_ExecTaskStreamingClient, error) {
	stream, err := c.cc.NewStream(ctx, &Driver_ServiceDesc.Streams[3], "/hashicorp.nomad.plugins.drivers.proto.Driver/ExecTaskStreaming", opts...)
	if err != nil {
		return nil, err
	}
	x := &driverExecTaskStreamingClient{stream}
	return x, nil
}

type Driver_ExecTaskStreamingClient interface {
	Send(*ExecTaskStreamingRequest) error
	Recv() (*ExecTaskStreamingResponse, error)
	grpc.ClientStream
}

type driverExecTaskStreamingClient struct {
	grpc.ClientStream
}

func (x *driverExecTaskStreamingClient) Send(m *ExecTaskStreamingRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *driverExecTaskStreamingClient) Recv() (*ExecTaskStreamingResponse, error) {
	m := new(ExecTaskStreamingResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *driverClient) CreateNetwork(ctx context.Context, in *CreateNetworkRequest, opts ...grpc.CallOption) (*CreateNetworkResponse, error) {
	out := new(CreateNetworkResponse)
	err := c.cc.Invoke(ctx, "/hashicorp.nomad.plugins.drivers.proto.Driver/CreateNetwork", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverClient) DestroyNetwork(ctx context.Context, in *DestroyNetworkRequest, opts ...grpc.CallOption) (*DestroyNetworkResponse, error) {
	out := new(DestroyNetworkResponse)
	err := c.cc.Invoke(ctx, "/hashicorp.nomad.plugins.drivers.proto.Driver/DestroyNetwork", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DriverServer is the server API for Driver service.
// All implementations should embed UnimplementedDriverServer
// for forward compatibility
type DriverServer interface {
	// TaskConfigSchema returns the schema for parsing the driver
	// configuration of a task.
	TaskConfigSchema(context.Context, *TaskConfigSchemaRequest) (*TaskConfigSchemaResponse, error)
	// Capabilities returns a set of features which the driver implements. Some
	// RPCs are not possible to implement on some runtimes, this allows the
	// driver to indicate if it doesn't support these RPCs and features.
	Capabilities(context.Context, *CapabilitiesRequest) (*CapabilitiesResponse, error)
	// Fingerprint starts a stream which emits information about the driver
	// including whether the driver healthy and able to function in the
	// existing environment.
	//
	// The driver should immediately stream a FingerprintResponse when the RPC
	// is initially called, then send any additional responses if there is a
	// change in the driver's state.
	Fingerprint(*FingerprintRequest, Driver_FingerprintServer) error
	// RecoverTask is used when a task has been started but the driver may not
	// know about it. Such is the case if the driver restarts or is upgraded.
	RecoverTask(context.Context, *RecoverTaskRequest) (*RecoverTaskResponse, error)
	// StartTask starts and tracks the task on the implemented runtime
	StartTask(context.Context, *StartTaskRequest) (*StartTaskResponse, error)
	// WaitTask blocks until the given task exits, returning the result of the
	// task. It may be called after the task has exited, but before the task is
	// destroyed.
	WaitTask(context.Context, *WaitTaskRequest) (*WaitTaskResponse, error)
	// StopTask stops a given task by sending the desired signal to the process.
	// If the task does not exit on its own within the given timeout, it will be
	// forcefully killed.
	StopTask(context.Context, *StopTaskRequest) (*StopTaskResponse, error)
	// DestroyTask removes the task from the driver's internal state and cleans
	// up any additional resources created by the driver. It cannot be called
	// on a running task, unless force is set to true.
	DestroyTask(context.Context, *DestroyTaskRequest) (*DestroyTaskResponse, error)
	// InspectTask returns detailed information for the given task
	InspectTask(context.Context, *InspectTaskRequest) (*InspectTaskResponse, error)
	// TaskStats collects and returns runtime metrics for the given task
	TaskStats(*TaskStatsRequest, Driver_TaskStatsServer) error
	// TaskEvents starts a streaming RPC where all task events emitted by the
	// driver are streamed to the caller.
	TaskEvents(*TaskEventsRequest, Driver_TaskEventsServer) error
	// SignalTask sends a signal to the task
	SignalTask(context.Context, *SignalTaskRequest) (*SignalTaskResponse, error)
	// ExecTask executes a command inside the tasks execution context
	ExecTask(context.Context, *ExecTaskRequest) (*ExecTaskResponse, error)
	// ExecTaskStreaming executes a command inside the tasks execution context
	// and streams back results
	// buf:lint:ignore RPC_REQUEST_RESPONSE_UNIQUE
	ExecTaskStreaming(Driver_ExecTaskStreamingServer) error
	// CreateNetwork is implemented when the driver needs to create the network
	// namespace instead of allowing the Nomad client to do.
	CreateNetwork(context.Context, *CreateNetworkRequest) (*CreateNetworkResponse, error)
	// DestroyNetwork destroys a previously created network. This rpc is only
	// implemented if the driver needs to manage network namespace creation.
	DestroyNetwork(context.Context, *DestroyNetworkRequest) (*DestroyNetworkResponse, error)
}

// UnimplementedDriverServer should be embedded to have forward compatible implementations.
type UnimplementedDriverServer struct {
}

func (UnimplementedDriverServer) TaskConfigSchema(context.Context, *TaskConfigSchemaRequest) (*TaskConfigSchemaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TaskConfigSchema not implemented")
}
func (UnimplementedDriverServer) Capabilities(context.Context, *CapabilitiesRequest) (*CapabilitiesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Capabilities not implemented")
}
func (UnimplementedDriverServer) Fingerprint(*FingerprintRequest, Driver_FingerprintServer) error {
	return status.Errorf(codes.Unimplemented, "method Fingerprint not implemented")
}
func (UnimplementedDriverServer) RecoverTask(context.Context, *RecoverTaskRequest) (*RecoverTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RecoverTask not implemented")
}
func (UnimplementedDriverServer) StartTask(context.Context, *StartTaskRequest) (*StartTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartTask not implemented")
}
func (UnimplementedDriverServer) WaitTask(context.Context, *WaitTaskRequest) (*WaitTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WaitTask not implemented")
}
func (UnimplementedDriverServer) StopTask(context.Context, *StopTaskRequest) (*StopTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopTask not implemented")
}
func (UnimplementedDriverServer) DestroyTask(context.Context, *DestroyTaskRequest) (*DestroyTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DestroyTask not implemented")
}
func (UnimplementedDriverServer) InspectTask(context.Context, *InspectTaskRequest) (*InspectTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InspectTask not implemented")
}
func (UnimplementedDriverServer) TaskStats(*TaskStatsRequest, Driver_TaskStatsServer) error {
	return status.Errorf(codes.Unimplemented, "method TaskStats not implemented")
}
func (UnimplementedDriverServer) TaskEvents(*TaskEventsRequest, Driver_TaskEventsServer) error {
	return status.Errorf(codes.Unimplemented, "method TaskEvents not implemented")
}
func (UnimplementedDriverServer) SignalTask(context.Context, *SignalTaskRequest) (*SignalTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignalTask not implemented")
}
func (UnimplementedDriverServer) ExecTask(context.Context, *ExecTaskRequest) (*ExecTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecTask not implemented")
}
func (UnimplementedDriverServer) ExecTaskStreaming(Driver_ExecTaskStreamingServer) error {
	return status.Errorf(codes.Unimplemented, "method ExecTaskStreaming not implemented")
}
func (UnimplementedDriverServer) CreateNetwork(context.Context, *CreateNetworkRequest) (*CreateNetworkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateNetwork not implemented")
}
func (UnimplementedDriverServer) DestroyNetwork(context.Context, *DestroyNetworkRequest) (*DestroyNetworkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DestroyNetwork not implemented")
}

// UnsafeDriverServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DriverServer will
// result in compilation errors.
type UnsafeDriverServer interface {
	mustEmbedUnimplementedDriverServer()
}

func RegisterDriverServer(s grpc.ServiceRegistrar, srv DriverServer) {
	s.RegisterService(&Driver_ServiceDesc, srv)
}

func _Driver_TaskConfigSchema_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskConfigSchemaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServer).TaskConfigSchema(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hashicorp.nomad.plugins.drivers.proto.Driver/TaskConfigSchema",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServer).TaskConfigSchema(ctx, req.(*TaskConfigSchemaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Driver_Capabilities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CapabilitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServer).Capabilities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hashicorp.nomad.plugins.drivers.proto.Driver/Capabilities",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServer).Capabilities(ctx, req.(*CapabilitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Driver_Fingerprint_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(FingerprintRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DriverServer).Fingerprint(m, &driverFingerprintServer{stream})
}

type Driver_FingerprintServer interface {
	Send(*FingerprintResponse) error
	grpc.ServerStream
}

type driverFingerprintServer struct {
	grpc.ServerStream
}

func (x *driverFingerprintServer) Send(m *FingerprintResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _Driver_RecoverTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecoverTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServer).RecoverTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hashicorp.nomad.plugins.drivers.proto.Driver/RecoverTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServer).RecoverTask(ctx, req.(*RecoverTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Driver_StartTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServer).StartTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hashicorp.nomad.plugins.drivers.proto.Driver/StartTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServer).StartTask(ctx, req.(*StartTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Driver_WaitTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WaitTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServer).WaitTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hashicorp.nomad.plugins.drivers.proto.Driver/WaitTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServer).WaitTask(ctx, req.(*WaitTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Driver_StopTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServer).StopTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hashicorp.nomad.plugins.drivers.proto.Driver/StopTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServer).StopTask(ctx, req.(*StopTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Driver_DestroyTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DestroyTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServer).DestroyTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hashicorp.nomad.plugins.drivers.proto.Driver/DestroyTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServer).DestroyTask(ctx, req.(*DestroyTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Driver_InspectTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InspectTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServer).InspectTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hashicorp.nomad.plugins.drivers.proto.Driver/InspectTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServer).InspectTask(ctx, req.(*InspectTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Driver_TaskStats_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(TaskStatsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DriverServer).TaskStats(m, &driverTaskStatsServer{stream})
}

type Driver_TaskStatsServer interface {
	Send(*TaskStatsResponse) error
	grpc.ServerStream
}

type driverTaskStatsServer struct {
	grpc.ServerStream
}

func (x *driverTaskStatsServer) Send(m *TaskStatsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _Driver_TaskEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(TaskEventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DriverServer).TaskEvents(m, &driverTaskEventsServer{stream})
}

type Driver_TaskEventsServer interface {
	Send(*DriverTaskEvent) error
	grpc.ServerStream
}

type driverTaskEventsServer struct {
	grpc.ServerStream
}

func (x *driverTaskEventsServer) Send(m *DriverTaskEvent) error {
	return x.ServerStream.SendMsg(m)
}

func _Driver_SignalTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignalTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServer).SignalTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hashicorp.nomad.plugins.drivers.proto.Driver/SignalTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServer).SignalTask(ctx, req.(*SignalTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Driver_ExecTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServer).ExecTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hashicorp.nomad.plugins.drivers.proto.Driver/ExecTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServer).ExecTask(ctx, req.(*ExecTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Driver_ExecTaskStreaming_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DriverServer).ExecTaskStreaming(&driverExecTaskStreamingServer{stream})
}

type Driver_ExecTaskStreamingServer interface {
	Send(*ExecTaskStreamingResponse) error
	Recv() (*ExecTaskStreamingRequest, error)
	grpc.ServerStream
}

type driverExecTaskStreamingServer struct {
	grpc.ServerStream
}

func (x *driverExecTaskStreamingServer) Send(m *ExecTaskStreamingResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *driverExecTaskStreamingServer) Recv() (*ExecTaskStreamingRequest, error) {
	m := new(ExecTaskStreamingRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Driver_CreateNetwork_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateNetworkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServer).CreateNetwork(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hashicorp.nomad.plugins.drivers.proto.Driver/CreateNetwork",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServer).CreateNetwork(ctx, req.(*CreateNetworkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Driver_DestroyNetwork_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DestroyNetworkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServer).DestroyNetwork(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hashicorp.nomad.plugins.drivers.proto.Driver/DestroyNetwork",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServer).DestroyNetwork(ctx, req.(*DestroyNetworkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Driver_ServiceDesc is the grpc.ServiceDesc for Driver service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Driver_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hashicorp.nomad.plugins.drivers.proto.Driver",
	HandlerType: (*DriverServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TaskConfigSchema",
			Handler:    _Driver_TaskConfigSchema_Handler,
		},
		{
			MethodName: "Capabilities",
			Handler:    _Driver_Capabilities_Handler,
		},
		{
			MethodName: "RecoverTask",
			Handler:    _Driver_RecoverTask_Handler,
		},
		{
			MethodName: "StartTask",
			Handler:    _Driver_StartTask_Handler,
		},
		{
			MethodName: "WaitTask",
			Handler:    _Driver_WaitTask_Handler,
		},
		{
			MethodName: "StopTask",
			Handler:    _Driver_StopTask_Handler,
		},
		{
			MethodName: "DestroyTask",
			Handler:    _Driver_DestroyTask_Handler,
		},
		{
			MethodName: "InspectTask",
			Handler:    _Driver_InspectTask_Handler,
		},
		{
			MethodName: "SignalTask",
			Handler:    _Driver_SignalTask_Handler,
		},
		{
			MethodName: "ExecTask",
			Handler:    _Driver_ExecTask_Handler,
		},
		{
			MethodName: "CreateNetwork",
			Handler:    _Driver_CreateNetwork_Handler,
		},
		{
			MethodName: "DestroyNetwork",
			Handler:    _Driver_DestroyNetwork_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Fingerprint",
			Handler:       _Driver_Fingerprint_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "TaskStats",
			Handler:       _Driver_TaskStats_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "TaskEvents",
			Handler:       _Driver_TaskEvents_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ExecTaskStreaming",
			Handler:       _Driver_ExecTaskStreaming_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "plugins/drivers/proto/driver.proto",
}
