// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DockerLoggerClient is the client API for DockerLogger service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DockerLoggerClient interface {
	Start(ctx context.Context, in *StartRequest, opts ...grpc.CallOption) (*StartResponse, error)
	Stop(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (*StopResponse, error)
}

type dockerLoggerClient struct {
	cc grpc.ClientConnInterface
}

func NewDockerLoggerClient(cc grpc.ClientConnInterface) DockerLoggerClient {
	return &dockerLoggerClient{cc}
}

func (c *dockerLoggerClient) Start(ctx context.Context, in *StartRequest, opts ...grpc.CallOption) (*StartResponse, error) {
	out := new(StartResponse)
	err := c.cc.Invoke(ctx, "/hashicorp.nomad.drivers.docker.docklog.proto.DockerLogger/Start", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dockerLoggerClient) Stop(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (*StopResponse, error) {
	out := new(StopResponse)
	err := c.cc.Invoke(ctx, "/hashicorp.nomad.drivers.docker.docklog.proto.DockerLogger/Stop", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DockerLoggerServer is the server API for DockerLogger service.
// All implementations should embed UnimplementedDockerLoggerServer
// for forward compatibility
type DockerLoggerServer interface {
	Start(context.Context, *StartRequest) (*StartResponse, error)
	Stop(context.Context, *StopRequest) (*StopResponse, error)
}

// UnimplementedDockerLoggerServer should be embedded to have forward compatible implementations.
type UnimplementedDockerLoggerServer struct {
}

func (UnimplementedDockerLoggerServer) Start(context.Context, *StartRequest) (*StartResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Start not implemented")
}
func (UnimplementedDockerLoggerServer) Stop(context.Context, *StopRequest) (*StopResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Stop not implemented")
}

// UnsafeDockerLoggerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DockerLoggerServer will
// result in compilation errors.
type UnsafeDockerLoggerServer interface {
	mustEmbedUnimplementedDockerLoggerServer()
}

func RegisterDockerLoggerServer(s grpc.ServiceRegistrar, srv DockerLoggerServer) {
	s.RegisterService(&DockerLogger_ServiceDesc, srv)
}

func _DockerLogger_Start_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DockerLoggerServer).Start(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hashicorp.nomad.drivers.docker.docklog.proto.DockerLogger/Start",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DockerLoggerServer).Start(ctx, req.(*StartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DockerLogger_Stop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DockerLoggerServer).Stop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hashicorp.nomad.drivers.docker.docklog.proto.DockerLogger/Stop",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DockerLoggerServer).Stop(ctx, req.(*StopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DockerLogger_ServiceDesc is the grpc.ServiceDesc for DockerLogger service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DockerLogger_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hashicorp.nomad.drivers.docker.docklog.proto.DockerLogger",
	HandlerType: (*DockerLoggerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Start",
			Handler:    _DockerLogger_Start_Handler,
		},
		{
			MethodName: "Stop",
			Handler:    _DockerLogger_Stop_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "drivers/docker/docklog/proto/docker_logger.proto",
}
